dist: trusty
language: java
cache:
  apt: true
  directories:
  - "$HOME/.m2"
  - "$HOME/.downloads"
sudo: true
jdk: openjdk11
# Build
script:
- mvn clean compile package install
# Deployment
deploy:
  provider: script
  script: mvn deploy --settings deploy/maven-settings.xml
  on:
    branch: master
    tags: false
env:
  global:
  - secure: jhKJdK36O/raB3i3yxoqkn8TLZquPdFte+Wt76M8MxK/bmQkwobFvISWmYy0mN0/X1f/ly6DysXMl6Xzj9WTaHcJMwnB5VY5ndc4gZqDZBk3DI7cceXn1zUCQa0wkZBItKQ25myg4gqKUXLU6HaBlsXRLqRJNjksT3ZNB0fmpJkPf1BJNurKO7zzmyb5ywrVBIupG2ETu9tGv4HudXMAvsPCphFGzdRwA0ndQpA8e8oKLXPUCTwULvTGJnA7B6k+H9X+hHpki53yjCdk5EzePBLIrXw+rUb5ijgNNIbflLcx/niALZgxc9CS2u2zJLPHVDiqtYa+wHakaPpJb2FMdBTjKXKccnlMlmetWAetRZh6PLzZMi5iVjM3RJvhcTMAAJBZ+eqoPNHiA1oDvPyzKrk5xLLCWvke/Zz/J7Ma0Afo3MSD+89/C2J703xYOcWuytYh8ijqbpF1SMwj8uDnm7iOxAIJYj6nIARHyDFm/bCfA0lQv/EbSRFy+DiFNoH1k7P5X5EwgM1h3EDiQPYpruZrZvv3JmXDp0/5q1UfWEvkM8A1w/IjXN7Iv6z+9S3PE/30MdGWN3r7SXN5tvOwVwYj0D5l4TG3/4Vg3jy0yFAnV9zpBIl7zEs/kpEzgF5my3c8b4kR7JXf5Vig0sp4D26KSvSLg/HEr9vXcnog9vQ=
  - secure: aAPKLZH94AOvmBOumjRMYJECjDiCakqWHBXPkYQxr/wdCcUTbeUCTGgavyO8JMOeBtFdItkrptXGW7T9rNchpB79naJr5AeHSXADuaiSzCQmLWEJh6Hj/M7veqr/iKKJnM314TaIGALnhhOTqh9hmUwLg7bfUkU3BsuqDAQswQuMqrncETeOmubXT/Qt6D5HJhkKt4ARHH3b06KEsuhsui0mzqA1hTbRemMf/r+Yf16Itd2O+EsmPRQ45fk1mS5e3kLG8id9ykD8IbfNG25JGqotVqnSFTj6OkmkU7MdMCSHYPTJblYa6CJc2lzwDtDOD5Hezdmt3EetwPkziVwmg5O4zQ+QRmEKdisvTym/WYaroUB7xpSoJFLajVL4L4KC7h7GZGRf8Yjx+VAwffgrGTkJtc+gIH3oE7EaVHqkt/pIwxLVyLqRrlGlPqK6IER9pG6K/DIZbizbpfnbsMv8Zt2ngpxUJ00eMhuggkDDEeNrM/DKnWuTewT96J02+p4yb59cULw8K2UKaEcTg4EMzDhKWUHJdw0f06dx0lj2+e+mJuyYWlio6KojKAmHqr/phX3A8sXkWj8gbFrJXiCBPq2bZkRHDnSc43WFsdXvIob6Nof0tfbukFAF5sWhFCJ8pKaMSpBaTomfXgXvnfcy6j75X+I+i3lBqNJ0LQkv22g=
